name=Somnia
version=0.4.0
author=Core Red Project
maintainer=HoujouSxnnyside
sentence=Deterministic zero-allocation procedural audio generator for AVR microcontrollers.
paragraph=A portable zero-dependency procedural melody generation engine designed to stream infinite oníric landscapes into resource-constrained systems without heap allocations.
category=Audio
url=https://github.com/core-red-project/somnia
architectures=avr,samd,esp32,rp2040,*
