; PlatformIO Project Configuration File for Somnia Hardware Target
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
include_dir = .

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -std=gnu++17 -O3 -Wall

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -std=gnu++17 -O3 -Wall

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -std=gnu++20 -O3 -Wall

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
build_flags = -std=gnu++20 -O3 -Wall
